FROM node:16-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY package*.json ./
#USER node
#VOLUME [ "./save-videos","/home/node/app/save-videos" ]
RUN npm install
COPY --chown=node:node . .
EXPOSE 3001
CMD [ "node", "nvr-browser.js" ]